#### Seems to be a 400 bad request when POST to https://{id}.execute-api.eu-west-1.amazonaws.com/prod/submission/algo

In [10]:
id_token_name="CognitoIdentityServiceProvider.32c5dc5t1kl51edcqv39i0r2s2.rzhan@andrew.cmu.edu.idToken"
id_token="eyJraWQiOiJ4M3NhZjFZTkNsRGwyVDljemdCR01ybnVVMlJlNDNjb1E1UGxYMWgwb2tBPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjYTZiMzZkMy1kZGU4LTQwMTQtYmQ2MS04NzcwODM2MDY2ODkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMS5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTFfek9mVngwcWl3IiwiY29nbml0bzp1c2VybmFtZSI6ImNhNmIzNmQzLWRkZTgtNDAxNC1iZDYxLTg3NzA4MzYwNjY4OSIsIm9yaWdpbl9qdGkiOiI2ZjUxYjVmOC1mNjA2LTQyNWMtYjlkNS1lNDY1Y2E5ZmUzMzAiLCJhdWQiOiIzMmM1ZGM1dDFrbDUxZWRjcXYzOWkwcjJzMiIsImV2ZW50X2lkIjoiNGE4MDE5ZGMtNWIzOS00NWViLWJlNTQtN2NmMDRlMmRkMDQ4IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NzkyNzY1NjksImV4cCI6MTY3OTM3NjE0OSwiaWF0IjoxNjc5MzcyNTQ5LCJqdGkiOiI3MjY1OGU4NC1mMmE3LTRhZWMtOTA5Yy0xMzljNjYwODliNTUiLCJlbWFpbCI6InJ6aGFuQGFuZHJldy5jbXUuZWR1In0.i0Fom-6_CyHaeeOrXz6elEHPQ87HJbDkFex48CJ16xAoMSDLBDLb0N45OK4_fgdHuaFNOkPcM_XpV104QFHSCA-NBxrf_xoH3zMzpgaHFwihBG4yJIp8IjjW3rTo7sIbJBKQj-oa26bEOmDxpyJrUMJposRpVkHoMABXOsFKv99e9jVtNrpRoH4oPgll6Ft31NSKonnMJ0VvWSM3epQa0ef7YpyeVC7gxS0FLgBH8d1qfj2sVOr0xM4iPYOS2TSYmTs-jcbcRom362Sz8aX777fqHbukEza31GKaxY2dEkVfh6L7CUS6TeQJvR8u8Lh9VULNkKCmddai05Ur-weAOw"

In [20]:
f"Bearer {id_token_name}={id_token}"

'Bearer CognitoIdentityServiceProvider.32c5dc5t1kl51edcqv39i0r2s2.rzhan@andrew.cmu.edu.idToken=eyJraWQiOiJ4M3NhZjFZTkNsRGwyVDljemdCR01ybnVVMlJlNDNjb1E1UGxYMWgwb2tBPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjYTZiMzZkMy1kZGU4LTQwMTQtYmQ2MS04NzcwODM2MDY2ODkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMS5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTFfek9mVngwcWl3IiwiY29nbml0bzp1c2VybmFtZSI6ImNhNmIzNmQzLWRkZTgtNDAxNC1iZDYxLTg3NzA4MzYwNjY4OSIsIm9yaWdpbl9qdGkiOiI2ZjUxYjVmOC1mNjA2LTQyNWMtYjlkNS1lNDY1Y2E5ZmUzMzAiLCJhdWQiOiIzMmM1ZGM1dDFrbDUxZWRjcXYzOWkwcjJzMiIsImV2ZW50X2lkIjoiNGE4MDE5ZGMtNWIzOS00NWViLWJlNTQtN2NmMDRlMmRkMDQ4IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NzkyNzY1NjksImV4cCI6MTY3OTM3NjE0OSwiaWF0IjoxNjc5MzcyNTQ5LCJqdGkiOiI3MjY1OGU4NC1mMmE3LTRhZWMtOTA5Yy0xMzljNjYwODliNTUiLCJlbWFpbCI6InJ6aGFuQGFuZHJldy5jbXUuZWR1In0.i0Fom-6_CyHaeeOrXz6elEHPQ87HJbDkFex48CJ16xAoMSDLBDLb0N45OK4_fgdHuaFNOkPcM_XpV104QFHSCA-NBxrf_xoH3zMzpgaHFwihBG4yJIp8IjjW3rTo7sIbJBKQj-oa26bEOmDxpyJrUMJposRpVkHoM

In [19]:
import requests

log_id = "8d256601-b8cc-428c-b14a-5f204d315125"

algo_id = "9ee5a984-2102-4ca5-9920-0c8052ee14cb"
email = "rzhan@andrew.cmu.edu"
headers = {
    "Authorization": f"Bearer {id_token_name}={id_token}"
}

url = f"https://bz97lt8b1e.execute-api.eu-west-1.amazonaws.com/prod/results/tutorial/{algo_id}"

print(url)

response = requests.post(
    url=url,
    headers=headers,
)

if __name__ == '__main__':
    print(response.json())

https://bz97lt8b1e.execute-api.eu-west-1.amazonaws.com/prod/results/tutorial/9ee5a984-2102-4ca5-9920-0c8052ee14cb
{'message': 'Forbidden'}


In [21]:
import numpy as np

In [22]:
mat = np.array([
    [1, 0.5, 1.45, 0.75],
    [1.95, 1, 3.1, 1.49],
    [0.67, 0.31, 1, 0.48],
    [1.34, 0.64, 1.98, 1],
])

In [37]:
cur = np.array([0, 0, 0, 1])

for i in range(5):
    cur = cur.reshape(4, 1)
    res = (mat * cur).T
    inds = np.argmax(res, axis=1)
    cur = np.max(res, axis=1)
    print("iter", i)
    display(res)
    display(inds)
    display(cur)

iter 0


array([[0.  , 0.  , 0.  , 1.34],
       [0.  , 0.  , 0.  , 0.64],
       [0.  , 0.  , 0.  , 1.98],
       [0.  , 0.  , 0.  , 1.  ]])

array([3, 3, 3, 3])

array([1.34, 0.64, 1.98, 1.  ])

iter 1


array([[1.34  , 1.248 , 1.3266, 1.34  ],
       [0.67  , 0.64  , 0.6138, 0.64  ],
       [1.943 , 1.984 , 1.98  , 1.98  ],
       [1.005 , 0.9536, 0.9504, 1.    ]])

array([0, 0, 1, 0])

array([1.34 , 0.67 , 1.984, 1.005])

iter 2


array([[1.34   , 1.3065 , 1.32928, 1.3467 ],
       [0.67   , 0.67   , 0.61504, 0.6432 ],
       [1.943  , 2.077  , 1.984  , 1.9899 ],
       [1.005  , 0.9983 , 0.95232, 1.005  ]])

array([3, 0, 1, 0])

array([1.3467, 0.67  , 2.077 , 1.005 ])

iter 3


array([[1.3467  , 1.3065  , 1.39159 , 1.3467  ],
       [0.67335 , 0.67    , 0.64387 , 0.6432  ],
       [1.952715, 2.077   , 2.077   , 1.9899  ],
       [1.010025, 0.9983  , 0.99696 , 1.005   ]])

array([2, 0, 1, 0])

array([1.39159 , 0.67335 , 2.077   , 1.010025])

iter 4


array([[1.39159  , 1.3130325, 1.39159  , 1.3534335],
       [0.695795 , 0.67335  , 0.64387  , 0.646416 ],
       [2.0178055, 2.087385 , 2.077    , 1.9998495],
       [1.0436925, 1.0032915, 0.99696  , 1.010025 ]])

array([0, 0, 1, 0])

array([1.39159  , 0.695795 , 2.087385 , 1.0436925])

In [1]:
import numpy as np

In [2]:
x = [1, 2, 3, 4]
y = [1, 4, 9, 16]



In [5]:
model = np.poly1d(np.polyfit(x, y, deg=2))

In [9]:
model(5)

25.000000000000007

In [1]:
import pandas as pd


In [29]:
pos1 = pd.read_csv("./my_positions_1.csv")
pos2 = pd.read_csv("./my_positions_2.csv")

fairs1 = pd.read_csv("./fairs_1.csv")
fairs2 = pd.read_csv("./fairs_2.csv")



In [30]:
col = "PEARLS_pnl"

inds = abs(pos1[col] - pos2[col]) > 1e-5

display(pos1[inds].iloc[:10])
display(pos2[inds].iloc[:10])

Unnamed: 0  BANANAS  BANANAS_cash  COCONUTS  COCONUTS_cash  PEARLS  \
299         299      2.0       -9300.0     531.0     -4244412.0     5.0   
954         954     -7.0       35879.0     600.0     -4795496.0   -15.0   
955         955     -8.0       40764.0     600.0     -4795496.0   -19.0   
956         956     -8.0       40764.0     600.0     -4795496.0   -19.0   
957         957    -12.0       60304.0     600.0     -4795496.0   -20.0   
958         958    -12.0       60304.0     600.0     -4795496.0   -20.0   
959         959    -12.0       60304.0     600.0     -4795496.0   -20.0   
960         960    -12.0       60304.0     600.0     -4795496.0   -20.0   
961         961    -12.0       60304.0     600.0     -4795496.0   -19.0   
962         962    -12.0       60304.0     600.0     -4795496.0   -19.0   

     PEARLS_cash  PINA_COLADAS  PINA_COLADAS_cash   time  total_cash  turn  \
299     -49475.5         300.0         -4493911.0  29900  -8797098.5   299   
954     151562.5         300.0         -4494107.0  95400  -9102161.5   954   
955     191567.5         300.0         -4494107.0  95500  -9057271.5   955   
956     191567.5         300.0         -4494107.0  95600  -9057271.5   956   
957     201569.5         300.0         -4494107.0  95700  -9027729.5   957   
958     201569.5         300.0         -4494107.0  95800  -9027729.5   958   
959     201569.5         300.0         -4494107.0  95900  -9027729.5   959   
960     201569.5         300.0         -4494107.0  96000  -9027729.5   960   
961     191571.5         300.0         -4494107.0  96100  -9037727.5   961   
962     191571.5         300.0         -4494107.0  96200  -9037727.5   962   

     total_pnl  BANANAS_pnl  PEARLS_pnl  COCONUTS_pnl  PINA_COLADAS_pnl  \
299   -10479.0        438.0       524.5       -3580.5           -7861.0   
954   -15296.0       1694.5      1562.5      -13196.0           -5357.0   
955   -14381.5       1704.0      1567.5      -11996.0           -5657.0   
956   -14381.5       1704.0      1567.5      -11996.0           -5657.0   
957   -14219.5       1714.0      1569.5      -11996.0           -5507.0   
958   -11981.5       1702.0      1569.5      -10796.0           -4457.0   
959   -11381.5       1702.0      1569.5      -10196.0           -4457.0   
960   -11369.5       1714.0      1569.5      -10196.0           -4457.0   
961   -11523.5       1708.0      1571.5      -10196.0           -4607.0   
962   -12417.5       1714.0      1571.5      -10796.0           -4907.0   

     COCO_PINA_pnl  
299       -11441.5  
954       -18553.0  
955       -17653.0  
956       -17653.0  
957       -17503.0  
958       -15253.0  
959       -14653.0  
960       -14653.0  
961       -14803.0  
962       -15703.0

Unnamed: 0  BANANAS  BANANAS_cash  COCONUTS  COCONUTS_cash  PEARLS  \
299         299      2.0       -9300.0     531.0     -4244412.0     5.0   
954         954     -7.0       35879.0     600.0     -4795496.0   -15.0   
955         955     -8.0       40764.0     600.0     -4795496.0   -19.0   
956         956     -8.0       40764.0     600.0     -4795496.0   -19.0   
957         957    -12.0       60304.0     600.0     -4795496.0   -20.0   
958         958    -12.0       60304.0     600.0     -4795496.0   -20.0   
959         959    -12.0       60304.0     600.0     -4795496.0   -20.0   
960         960    -12.0       60304.0     600.0     -4795496.0   -20.0   
961         961    -12.0       60304.0     600.0     -4795496.0   -19.0   
962         962    -12.0       60304.0     600.0     -4795496.0   -19.0   

     PEARLS_cash  PINA_COLADAS  PINA_COLADAS_cash   time  total_cash  turn  \
299     -49470.0         300.0         -4493911.0  29900  -8797093.0   299   
954     151568.5         300.0         -4494107.0  95400  -9102155.5   954   
955     191576.5         300.0         -4494107.0  95500  -9057262.5   955   
956     191576.5         300.0         -4494107.0  95600  -9057262.5   956   
957     201578.5         300.0         -4494107.0  95700  -9027720.5   957   
958     201578.5         300.0         -4494107.0  95800  -9027720.5   958   
959     201578.5         300.0         -4494107.0  95900  -9027720.5   959   
960     201578.5         300.0         -4494107.0  96000  -9027720.5   960   
961     191580.5         300.0         -4494107.0  96100  -9037718.5   961   
962     191580.5         300.0         -4494107.0  96200  -9037718.5   962   

     total_pnl  BANANAS_pnl  PEARLS_pnl  COCONUTS_pnl  PINA_COLADAS_pnl  
299   -10473.5        438.0       530.0       -3580.5           -7861.0  
954   -15290.0       1694.5      1568.5      -13196.0           -5357.0  
955   -14372.5       1704.0      1576.5      -11996.0           -5657.0  
956   -14372.5       1704.0      1576.5      -11996.0           -5657.0  
957   -14210.5       1714.0      1578.5      -11996.0           -5507.0  
958   -11972.5       1702.0      1578.5      -10796.0           -4457.0  
959   -11372.5       1702.0      1578.5      -10196.0           -4457.0  
960   -11360.5       1714.0      1578.5      -10196.0           -4457.0  
961   -11514.5       1708.0      1580.5      -10196.0           -4607.0  
962   -12408.5       1714.0      1580.5      -10796.0           -4907.0

In [24]:
fairs1

Unnamed: 0   time  BANANAS  COCONUTS   PEARLS  PINA_COLADAS
0             0      0   4873.5    8004.5  10000.0       15014.0
1             1    100   4873.5    8003.5  10000.0       15012.0
2             2    200   4873.0    8004.5  10000.0       15016.0
3             3    300   4871.5    8004.5  10000.0       15015.5
4             4    400   4872.0    8003.5  10000.0       15013.5
..          ...    ...      ...       ...      ...           ...
995         995  99500   4882.5    7981.5  10000.0       14968.5
996         996  99600   4881.5    7980.5  10000.0       14964.5
997         997  99700   4881.5    7982.5  10000.0       14966.5
998         998  99800   4881.5    7983.5  10000.0       14968.0
999         999  99900   4882.5    7981.5  10000.0       14965.5

[1000 rows x 6 columns]

In [31]:
col = "PEARLS"

inds = abs(fairs1[col] - fairs2[col]) > 1e-5

display(fairs1[inds])
display(fairs2[inds])

Empty DataFrame
Columns: [Unnamed: 0, time, BANANAS, COCONUTS, PEARLS, PINA_COLADAS]
Index: []

Empty DataFrame
Columns: [Unnamed: 0, time, BANANAS, COCONUTS, PEARLS, PINA_COLADAS]
Index: []