#### Seems to be a 400 bad request when POST to https://{id}.execute-api.eu-west-1.amazonaws.com/prod/submission/algo

In [10]:
id_token_name="CognitoIdentityServiceProvider.32c5dc5t1kl51edcqv39i0r2s2.rzhan@andrew.cmu.edu.idToken"
id_token="eyJraWQiOiJ4M3NhZjFZTkNsRGwyVDljemdCR01ybnVVMlJlNDNjb1E1UGxYMWgwb2tBPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjYTZiMzZkMy1kZGU4LTQwMTQtYmQ2MS04NzcwODM2MDY2ODkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMS5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTFfek9mVngwcWl3IiwiY29nbml0bzp1c2VybmFtZSI6ImNhNmIzNmQzLWRkZTgtNDAxNC1iZDYxLTg3NzA4MzYwNjY4OSIsIm9yaWdpbl9qdGkiOiI2ZjUxYjVmOC1mNjA2LTQyNWMtYjlkNS1lNDY1Y2E5ZmUzMzAiLCJhdWQiOiIzMmM1ZGM1dDFrbDUxZWRjcXYzOWkwcjJzMiIsImV2ZW50X2lkIjoiNGE4MDE5ZGMtNWIzOS00NWViLWJlNTQtN2NmMDRlMmRkMDQ4IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NzkyNzY1NjksImV4cCI6MTY3OTM3NjE0OSwiaWF0IjoxNjc5MzcyNTQ5LCJqdGkiOiI3MjY1OGU4NC1mMmE3LTRhZWMtOTA5Yy0xMzljNjYwODliNTUiLCJlbWFpbCI6InJ6aGFuQGFuZHJldy5jbXUuZWR1In0.i0Fom-6_CyHaeeOrXz6elEHPQ87HJbDkFex48CJ16xAoMSDLBDLb0N45OK4_fgdHuaFNOkPcM_XpV104QFHSCA-NBxrf_xoH3zMzpgaHFwihBG4yJIp8IjjW3rTo7sIbJBKQj-oa26bEOmDxpyJrUMJposRpVkHoMABXOsFKv99e9jVtNrpRoH4oPgll6Ft31NSKonnMJ0VvWSM3epQa0ef7YpyeVC7gxS0FLgBH8d1qfj2sVOr0xM4iPYOS2TSYmTs-jcbcRom362Sz8aX777fqHbukEza31GKaxY2dEkVfh6L7CUS6TeQJvR8u8Lh9VULNkKCmddai05Ur-weAOw"

In [20]:
f"Bearer {id_token_name}={id_token}"

'Bearer CognitoIdentityServiceProvider.32c5dc5t1kl51edcqv39i0r2s2.rzhan@andrew.cmu.edu.idToken=eyJraWQiOiJ4M3NhZjFZTkNsRGwyVDljemdCR01ybnVVMlJlNDNjb1E1UGxYMWgwb2tBPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjYTZiMzZkMy1kZGU4LTQwMTQtYmQ2MS04NzcwODM2MDY2ODkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMS5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTFfek9mVngwcWl3IiwiY29nbml0bzp1c2VybmFtZSI6ImNhNmIzNmQzLWRkZTgtNDAxNC1iZDYxLTg3NzA4MzYwNjY4OSIsIm9yaWdpbl9qdGkiOiI2ZjUxYjVmOC1mNjA2LTQyNWMtYjlkNS1lNDY1Y2E5ZmUzMzAiLCJhdWQiOiIzMmM1ZGM1dDFrbDUxZWRjcXYzOWkwcjJzMiIsImV2ZW50X2lkIjoiNGE4MDE5ZGMtNWIzOS00NWViLWJlNTQtN2NmMDRlMmRkMDQ4IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NzkyNzY1NjksImV4cCI6MTY3OTM3NjE0OSwiaWF0IjoxNjc5MzcyNTQ5LCJqdGkiOiI3MjY1OGU4NC1mMmE3LTRhZWMtOTA5Yy0xMzljNjYwODliNTUiLCJlbWFpbCI6InJ6aGFuQGFuZHJldy5jbXUuZWR1In0.i0Fom-6_CyHaeeOrXz6elEHPQ87HJbDkFex48CJ16xAoMSDLBDLb0N45OK4_fgdHuaFNOkPcM_XpV104QFHSCA-NBxrf_xoH3zMzpgaHFwihBG4yJIp8IjjW3rTo7sIbJBKQj-oa26bEOmDxpyJrUMJposRpVkHoM

In [19]:
import requests

log_id = "8d256601-b8cc-428c-b14a-5f204d315125"

algo_id = "9ee5a984-2102-4ca5-9920-0c8052ee14cb"
email = "rzhan@andrew.cmu.edu"
headers = {
    "Authorization": f"Bearer {id_token_name}={id_token}"
}

url = f"https://bz97lt8b1e.execute-api.eu-west-1.amazonaws.com/prod/results/tutorial/{algo_id}"

print(url)

response = requests.post(
    url=url,
    headers=headers,
)

if __name__ == '__main__':
    print(response.json())

https://bz97lt8b1e.execute-api.eu-west-1.amazonaws.com/prod/results/tutorial/9ee5a984-2102-4ca5-9920-0c8052ee14cb
{'message': 'Forbidden'}


In [21]:
import numpy as np

In [22]:
mat = np.array([
    [1, 0.5, 1.45, 0.75],
    [1.95, 1, 3.1, 1.49],
    [0.67, 0.31, 1, 0.48],
    [1.34, 0.64, 1.98, 1],
])

In [37]:
cur = np.array([0, 0, 0, 1])

for i in range(5):
    cur = cur.reshape(4, 1)
    res = (mat * cur).T
    inds = np.argmax(res, axis=1)
    cur = np.max(res, axis=1)
    print("iter", i)
    display(res)
    display(inds)
    display(cur)

iter 0


array([[0.  , 0.  , 0.  , 1.34],
       [0.  , 0.  , 0.  , 0.64],
       [0.  , 0.  , 0.  , 1.98],
       [0.  , 0.  , 0.  , 1.  ]])

array([3, 3, 3, 3])

array([1.34, 0.64, 1.98, 1.  ])

iter 1


array([[1.34  , 1.248 , 1.3266, 1.34  ],
       [0.67  , 0.64  , 0.6138, 0.64  ],
       [1.943 , 1.984 , 1.98  , 1.98  ],
       [1.005 , 0.9536, 0.9504, 1.    ]])

array([0, 0, 1, 0])

array([1.34 , 0.67 , 1.984, 1.005])

iter 2


array([[1.34   , 1.3065 , 1.32928, 1.3467 ],
       [0.67   , 0.67   , 0.61504, 0.6432 ],
       [1.943  , 2.077  , 1.984  , 1.9899 ],
       [1.005  , 0.9983 , 0.95232, 1.005  ]])

array([3, 0, 1, 0])

array([1.3467, 0.67  , 2.077 , 1.005 ])

iter 3


array([[1.3467  , 1.3065  , 1.39159 , 1.3467  ],
       [0.67335 , 0.67    , 0.64387 , 0.6432  ],
       [1.952715, 2.077   , 2.077   , 1.9899  ],
       [1.010025, 0.9983  , 0.99696 , 1.005   ]])

array([2, 0, 1, 0])

array([1.39159 , 0.67335 , 2.077   , 1.010025])

iter 4


array([[1.39159  , 1.3130325, 1.39159  , 1.3534335],
       [0.695795 , 0.67335  , 0.64387  , 0.646416 ],
       [2.0178055, 2.087385 , 2.077    , 1.9998495],
       [1.0436925, 1.0032915, 0.99696  , 1.010025 ]])

array([0, 0, 1, 0])

array([1.39159  , 0.695795 , 2.087385 , 1.0436925])